# Site settings
title: Alexandra Kabak
email: alexkabak@live.ca
description: "BCIT Computer Systems Game Development graduate."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Alexandra Kabak

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LexaFayte
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/LexaFayte
  - title: resume
    url: https://drive.google.com/file/d/0B4v6hS2wiEy0RUhiS21Lazk1NzQ/view?usp=sharing
# Build settings
markdown: kramdown
permalink: pretty
